// cinterop header skeleton — generated by jni-binding-generator.py
// Source: NativeBridgeJni.kt  |  class NativeBridgeJni
// Replace placeholder function names with your actual C API.
#pragma once
#include <stdint.h>
#include <stdbool.h>

int64_t native_bridge_jni_native_create(const char* model_path, int32_t threads, bool use_gpu);
void native_bridge_jni_native_destroy(int64_t handle);
const char* native_bridge_jni_native_generate(int64_t handle, const char* prompt, int32_t max_tokens);
void* /* TODO: IntArray — return via out-param or opaque handle */ native_bridge_jni_native_tokenize(int64_t handle, const char* text);
const char* native_bridge_jni_native_detokenize(int64_t handle, const int32_t* tokens, int32_t tokens_len);
void* /* TODO: List<Float> — return via out-param or opaque handle */ native_bridge_jni_native_embed(int64_t handle, const char* text);
void* /* TODO: Map<String, String> — return via out-param or opaque handle */ native_bridge_jni_native_get_metadata(int64_t handle);
void* /* TODO: Map<String, Float> — return via out-param or opaque handle */ native_bridge_jni_native_get_sampler_params(int64_t handle);
void native_bridge_jni_native_set_sampler_params(int64_t handle, float temperature, float top_p, int32_t top_k);
int32_t native_bridge_jni_native_get_vocab_size(int64_t handle);
int32_t native_bridge_jni_native_get_context_size(int64_t handle);
