// AUTO-GENERATED by jni-binding-generator.py --kotlin-from-header — DO NOT EDIT.
// Source: image_classifier.h
//
// Review every signature before use:
//   - void* params are mapped to Long (opaque native handle convention)
//   - Pointer-array params (float*, int32_t* …) are mapped to *Array
//   - Params/returns marked TODO could not be mapped — fill them in manually
//
// Load the native library once (add to the companion object or Application):
//   System.loadLibrary("imageclassifier")

package com.example.android.classifier

object ImageClassifier {

    external fun imageClassifierCreate(modelPath: String, threads: Int, useGpu: Boolean): Long
    external fun imageClassifierDestroy(handle: Long)
    external fun imageClassifierClassify(handle: Long, pixels: ByteArray, width: Int, height: Int, scores: FloatArray, numClasses: Int): Int
    external fun imageClassifierNumClasses(handle: Long): Int
    external fun imageClassifierGetLabel(handle: Long, classIndex: Int, buf: String, bufLen: Int): Int
    external fun imageClassifierVersion(handle: Long): String
    external fun imageClassifierSetOption(handle: Long, key: String, value: Float)
    external fun imageClassifierGetOption(handle: Long, key: String): Float
}
