from __future__ import annotations

import re
from pathlib import Path

from _models import ParsedFile

_RE_CAMEL = re.compile(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])")


def _camel_to_snake(name: str) -> str:
    return _RE_CAMEL.sub("_", name).lower()


def _kotlin_to_c_param(kotlin_type: str, param_name: str) -> str:
    """Return a C parameter declaration for a Kotlin type."""
    base = kotlin_type.rstrip("?").strip()
    simple = {
        "Int": f"int32_t {param_name}",
        "Long": f"int64_t {param_name}",
        "Float": f"float {param_name}",
        "Double": f"double {param_name}",
        "Boolean": f"bool {param_name}",
        "Short": f"int16_t {param_name}",
        "Byte": f"int8_t {param_name}",
        "String": f"const char* {param_name}",
    }
    if base in simple:
        return simple[base]
    array_elem = {
        "ByteArray": "const uint8_t*",
        "IntArray": "const int32_t*",
        "FloatArray": "const float*",
        "LongArray": "const int64_t*",
        "DoubleArray": "const double*",
        "BooleanArray": "const bool*",
        "ShortArray": "const int16_t*",
    }
    if base in array_elem:
        return f"{array_elem[base]} {param_name}, int32_t {param_name}_len"
    return f"void* {param_name} /* TODO: {base} — define a C struct */"


def _kotlin_return_to_c(kotlin_type: str | None) -> str:
    """Return the C return type for a Kotlin return type."""
    if kotlin_type is None:
        return "void"
    base = kotlin_type.rstrip("?").strip()
    simple = {
        "Int": "int32_t",
        "Long": "int64_t",
        "Float": "float",
        "Double": "double",
        "Boolean": "bool",
        "Short": "int16_t",
        "Byte": "int8_t",
        "String": "const char*",
    }
    if base in simple:
        return simple[base]
    return f"void* /* TODO: {base} — return via out-param or opaque handle */"


def generate_ios_cinterop_files(
    parsed_files: list[tuple[Path, ParsedFile]], output_dir: Path
) -> None:
    """Write a Kotlin/Native .def file + C header skeleton for each parsed file."""
    output_dir.mkdir(parents=True, exist_ok=True)
    include_dir = output_dir / "include"
    include_dir.mkdir(exist_ok=True)

    for kt, parsed in parsed_files:
        cls = parsed.class_name
        prefix = _camel_to_snake(cls)

        # --- C header ---
        header_lines = [
            "// cinterop header skeleton — generated by jni-binding-generator.py",
            f"// Source: {kt.name}  |  class {cls}",
            "// Replace placeholder function names with your actual C API.",
            "#pragma once",
            "#include <stdint.h>",
            "#include <stdbool.h>",
            "",
        ]
        for func in parsed.functions:
            fn_c = f"{prefix}_{_camel_to_snake(func.name)}"
            ret_c = _kotlin_return_to_c(func.return_type)
            params = [
                _kotlin_to_c_param(p.kotlin_type, _camel_to_snake(p.name)) for p in func.params
            ]
            params_str = ", ".join(params) if params else "void"
            header_lines.append(f"{ret_c} {fn_c}({params_str});")

        header_content = "\n".join(header_lines) + "\n"
        header_path = include_dir / f"{cls}.h"
        header_existing = header_path.read_text(encoding="utf-8") if header_path.exists() else None
        if header_existing != header_content:
            header_path.write_text(header_content, encoding="utf-8")

        # --- .def file ---
        def_lines = [
            "# Kotlin/Native cinterop definition — generated by jni-binding-generator.py",
            f"# Source class: {parsed.package}.{cls}",
            "#",
            "# Steps:",
            f"#  1. Rename functions in include/{cls}.h to match your actual C API.",
            "#  2. Point staticLibraries/libraryPaths at your compiled native library.",
            "#  3. In shared/build.gradle.kts (iosMain):",
            f"#       cinterops {{ val {prefix} by creating {{",
            f'#         defFile("src/nativeInterop/cinterop/{cls}.def")',
            "#       } }",
            "",
            f"headers = include/{cls}.h",
            "headerFilter = include/**",
            "",
            f"# staticLibraries = lib{prefix}.a",
            "# libraryPaths = /path/to/your/lib",
        ]
        def_content = "\n".join(def_lines) + "\n"
        def_path = output_dir / f"{cls}.def"
        def_existing = def_path.read_text(encoding="utf-8") if def_path.exists() else None
        if def_existing != def_content:
            def_path.write_text(def_content, encoding="utf-8")

        print(
            f"[cinterop] {kt.name}  ->  {def_path.name}  +  include/{cls}.h"
            f"  ({len(parsed.functions)} fn)"
        )
